-- NVL 함수
SELECT FIRST_NAME, salary, SALARY+SALARY*NVL(COMMISSION_PCT,0) as ann_sal
from EMPLOYEES
where SALARY != SALARY+SALARY*NVL(COMMISSION_PCT,0);


--NVL2 함수
SELECT FIRST_NAME, salary,nvl2(COMMIsSION_PCT, SALARY+(SALARY*COMMISsION_PCT), SALARY) AS ann_sal
from EMPLOYEES
where SALARY != SALARY+SALARY*NVL(COMMISSION_PCT,0);

--COALESCE 함수
SELECT FIRST_NAME, salary,COALESCE(SALARY+(SALARY*COMMISsION_PCT), salary) as ann_sal
from EMPLOYEES
where SALARY != SALARY+SALARY*NVL(COMMISSION_PCT,0);