-- UNION
SELECT EMPLOYEe_id, FIRST_NAME
from EMPLOYEES
where HIRE_DATE like '14%'
UNION
SELECT EMPLOYEE_ID, FIRST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 20;

--UNION ALL
SELECT employee_id, FIRST_NAME
from EMPLOYEES
where HIRE_DATE like '14%'
UNION ALL
SELECT EMPLOYEE_ID, FIRST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 20;

--INTERSECT
SELECT EMPLOYEe_id, FIRST_NAME
from EMPLOYEES
where HIRE_DATE like '14%'
INTERSECT
SELECT EMPLOYEE_ID, FIRST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 20;

SELECT EMPLOYEe_id, FIRST_NAME
from EMPLOYEES
where HIRE_DATE like '14%'
MINUS
SELECT EMPLOYEE_ID, FIRST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 20;