-- GROUP BY 사용
SELECT department_ID, AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

--하나 이상의 열로 그룹화
SELECT department_ID, job_id, sum(salary)
FROM EMPLOYEES
group by department_ID, job_id;

-- HAVING  사용
SELECT DEPARTMENT_ID, ROUND(AVG(SALARY),2) AS AVG_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY)>8000;

SELECT JOB_ID, AVG(SALARY) PAYROLL
FROM EMPLOYEES
WHERE JOB_ID NOT LIKE 'SA%'
GROUP BY JOB_ID
HAVING AVG(SALARY) > 8000
ORDER BY AVG(SALARY);