--ROLLUP
SELECT department_ID, job_id, ROUND(AVG(salary),2), COUNT(*)
FROM employees
GROUP BY ROLLUP(DEPARTMENT_ID, JOB_ID)
ORDER BY DEPARTMENT_ID, JOB_ID;


--CUBE
SELECT DEPARTMENT_ID, JOB_ID, ROUND(AVG(SALARY),2), COUNT(*)
FROM EMPLOYEES
GROUP BY CUBE(DEPARTMENT_ID, JOB_ID)
ORDER BY DEPARTMENT_ID, JOB_ID;