-- AVG, SUM, MIN, MAX 함수
SELECT MIN(salary), MAX(SALARY), SUM(SALARY), AVG(SALARY)
from EMPLOYEES
WHERE JOB_ID LIKE 'SA%';

-- COUNT 함수
SELECT COUNT(*) FROM EMPLOYEES;

SELECT COUNT(COMMISSION_PCT)
FROM EMPLOYEES;

-- STDDEV, VARIANCE 함수
SELECT SUM(SALARY) AS 합계,
    ROUND(AVG(SALARY),2) AS 평균,
    ROUND(STDDEV(SALARY)) AS 표준편차,
    ROUND(VARIANCE(SALARY)) AS 분산
FROM EMPLOYEES;