-- 1번 문제
SELECT EMPLOYEE_ID, FIRST_NAME, HIRE_DATE, SALARY
FROM EMPLOYEES;

-- 2번 문제
SELECT FIRST_NAME ||' ' ||LAST_NAME AS NAME
FROM EMPLOYEES;

-- 3번 문제
SELECT *
FROM EMPLOYEES
WHERE department_id = 50;

-- 4번 문제
SELECT FIRST_NAME, DEPARTMENT_ID, JOB_ID
FROM EMPLOYEES
WHERE department_id = 50;

-- 5번 문제
SELECT FIRST_NAME, SALARY, SALARY+300 
FROM EMPLOYEES;

-- 6번 문제
SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > 10000;

-- 7번 문제
SELECT FIRST_NAME, JOB_ID, COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL;

-- 8번 문제
SELECT FIRST_NAME, HIRE_DATE, SALARY
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '13/01/01' AND '13/12/31';

-- 9번 문제
SELECT FIRST_NAME, HIRE_DATE, SALARY
FROM EMPLOYEES
WHERE HIRE_DATE LIKE '13/%';

-- 10번 문제
SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC;

-- 11번 문제
SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 60
ORDER BY SALARY DESC;

-- 12번 문제
SELECT FIRST_NAME, JOB_ID
FROM EMPLOYEES
WHERE (JOB_ID = 'IT_PROG' OR JOB_ID='SA_MAN');

-- 13번 문제
SELECT FIRST_NAME ||' '||LAST_NAME|| ' 사원의 급여는 '||SALARY||'달러입니다' as "소개"
FROM EMPLOYEES
WHERE (LAST_NAME='King' and FIRST_NAME ='Steven');

-- 14번 문제
SELECT FIRST_NAME, JOB_ID
FROM EMPLOYEES
WHERE JOB_ID LIKE '%MAN%';

-- 15번 문제
SELECT FIRST_NAME, JOB_ID
FROM EMPLOYEES
WHERE JOB_ID LIKE '%MAN%'
ORDER BY JOB_ID;