SELECT first_name, hire_date
FROM EMPLOYEES
ORDER BY hire_date;

SELECT first_name, hire_date
FROM EMPLOYEES
ORDER BY hire_date DESC;

SELECT FIRST_NAME, SALARY*12 AS ANNSAL
FROM EMPLOYEES
ORDER BY ANNSAL;

SELECT FIRST_NAME, SALARY*12 AS ANNSAL
FROM EMPLOYEES
ORDER BY 2;